version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: mazuh
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: kiki_delivery
    ports:
      - "54342:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "alembic upgrade head && uvicorn kiki_delivery.application.web:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - .:/kiki_delivery
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_USER: mazuh
      DB_PASSWORD: devpass
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: kiki_delivery

volumes:
  db_data:
