"""my new migration

Revision ID: a3c0ba6480f5
Revises: ff7ca59b6125
Create Date: 2023-07-09 20:54:11.518854

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a3c0ba6480f5"
down_revision = "ff7ca59b6125"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("price", sa.String(length=10), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("picture", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
    INSERT INTO products (name, category, price, description, picture) VALUES
    ('Nachos Crocantes', 'SNACK', '20.00', 'Nachos deliciosamente queijosos e crocantes com um toque de especiarias.', ''),
    ('Mistura de Nozes', 'SNACK', '20.00', 'Uma mistura saudável e saborosa de amêndoas, castanhas de caju e pistaches.', ''),
    ('Batatas Doces Fritas', 'SIDE', '15.00', 'Batatas doces fritas, doces e salgadas com uma crocância perfeita.', ''),
    ('Pão de Alho', 'SIDE', '25.00', 'Pão de alho quente e crocante, um acompanhamento perfeito para qualquer refeição.', ''),
    ('Vitamina de Morango', 'DRINK', '20.00', 'Vitamina de morango refrescante com um equilíbrio perfeito de doce e ácido.', ''),
    ('Café Gelado', 'DRINK', '10.00', 'Café gelado forte e refrescante para animar seu dia.', ''),
    ('Sundae de Chocolate', 'DESSERT', '10.00', 'Entregue-se a um sundae de chocolate cremoso coberto com nozes e uma cereja.', ''),
    ('Cheesecake de Mirtilo', 'DESSERT', '15.00', 'Cheesecake cremoso com cobertura de mirtilo azedo.', '');
    """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
