"""my new migration

Revision ID: dd7bda6aacfb
Revises: a3c0ba6480f5
Create Date: 2023-07-09 23:51:03.915846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd7bda6aacfb"
down_revision = "a3c0ba6480f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=25), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_table(
        "orders_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_items_id"), "orders_items", ["id"], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
    INSERT INTO orders (status, received_at, customer_id) VALUES
    ('UNCONFIRMED', NULL, NULL),
    ('UNCONFIRMED', NULL, 1),
    ('RECEIVED', '2023-07-01 10:30:00', 2);
    """
    )

    op.execute(
        """
    INSERT INTO orders_items (order_id, product_id) VALUES
    (1, 1),
    (1, 3),
    (1, 5),
    (1, 7);
    """
    )
    op.execute(
        """
    INSERT INTO orders_items (order_id, product_id) VALUES
    (2, 2),
    (2, 4),
    (2, 6),
    (2, 8);
    """
    )
    op.execute(
        """
    INSERT INTO orders_items (order_id, product_id) VALUES
    (3, 1),
    (3, 3),
    (3, 5),
    (3, 7);
    """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_items_id"), table_name="orders_items")
    op.drop_table("orders_items")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
