"""add customer table

Revision ID: ff7ca59b6125
Revises: 
Create Date: 2023-07-09 18:04:57.955735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff7ca59b6125"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("cpf", sa.String(length=14), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_cpf"), "customers", ["cpf"], unique=False)
    op.create_index(op.f("ix_customers_id"), "customers", ["id"], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
    INSERT INTO customers (first_name, last_name, email, cpf) VALUES
    ('Jane', 'Doe', 'jane.doe@email.com', '111.111.111-11'),
    ('John', 'Doe', 'john.doe@email.com', '222.222.222-22');
    """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customers_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_cpf"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
