apiVersion: v1
kind: Service
metadata:
  name: kiki-delivery
spec:
  selector:
    app: kiki-delivery
    role: web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
